### ISSUE TITLE
RuntimeError: rays_o must be a CUDA tensor

### ISSUE THREAD

**Issue by antithing** [frozoul/4K-NeRF#15]
I run the example code run_sr, and I se ethe following error:

`python run_sr.py --config configs/llff/fern_lg_joint_l1+gan.py --render_test --ftdv_path logs/llff/pretrain_fern_l1/fine_last.tar --ftsr_path ./pretrained/RealESRNet_x4plus.pth --test_tile 510`

```
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to C:\Users\B/.cache\torch\hub\checkpoints\vgg19-dcbb9e9d.pth
100%|███████████████████████████████████████████████████████████████████████████████| 548M/548M [00:39<00:00, 14.5MB/s]
get_training_rays: start
get_training_rays: finish (eps time: 0.9931809902191162 sec)
  0%|                                                                                       | 0/270000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\NERF\4K-NeRF-main\4K-NeRF-main\run_sr.py", line 1294, in <module>
    train(args, cfg, data_dict)
  File "D:\NERF\4K-NeRF-main\4K-NeRF-main\run_sr.py", line 1220, in train
    scene_rep_reconstruction_sr_patch(
  File "D:\NERF\4K-NeRF-main\4K-NeRF-main\run_sr.py", line 870, in scene_rep_reconstruction_sr_patch
    render_result = model(
  File "C:\Users\B\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\NERF\4K-NeRF-main\4K-NeRF-main\lib\dmpigo.py", line 304, in forward
    ray_pts, ray_id, step_id, N_samples, mask_inbbox = self.sample_ray(
  File "D:\NERF\4K-NeRF-main\4K-NeRF-main\lib\dmpigo.py", line 279, in sample_ray
    ray_pts, mask_outbbox = render_utils_cuda.sample_ndc_pts_on_rays(
RuntimeError: rays_o must be a CUDA tensor
```

What might be causing this? Thanks!

**Comment by zhouilu** [comment]
default cuda cfg is os.environ["CUDA_VISIBLE_DEVICES"]="1", may be shoule '0'.
