### ISSUE TITLE
NULL ERRO

### ISSUE THREAD

**Issue by zf-666** [frozoul/4K-NeRF#9]
https://github.com/frozoul/4K-NeRF/blob/ddc40ef0ebeff0be87a079ae43e42d2841e06696/run_sr.py#L977

Traceback (most recent call last):
  File "/root/z50023003/4K-NeRF-main/run_sr.py", line 1294, in <module>
    train(args, cfg, data_dict)
  File "/root/z50023003/4K-NeRF-main/run_sr.py", line 1223, in train
    scene_rep_reconstruction_sr_patch(
  File "/root/z50023003/4K-NeRF-main/run_sr.py", line 991, in scene_rep_reconstruction_sr_patch
    loss_distortion = flatten_eff_distloss(w, s, 1/n_max, ray_id)
  File "/opt/conda/envs/mipnerf/lib/python3.9/site-packages/torch_efficient_distloss/eff_distloss.py", line 99, in forward
    n_rays = ray_id.max()+1
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

render_result['s'] & render_result['n_max'] & render_result['weights'] is NULL

**Comment by XLR-man** [comment]
Hello,what is your pytorch & cuda version?
